config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do
  resources :inbox_tables
  resources :app_schedules
  resources :special_requirements
  resources :app_times
  resources :app_durations
  resources :services
  resources :users, only: [:index]
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    devise_scope :user do
      post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  devise_for :users
  get 'active-sessions', to: "app_schedules#active_sessions"
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'app_schedules', to: 'model#app_schedules', defaults: { format: 'csv'}

end

app/controllers/inbox_tables_controller.rb
class InboxTablesController < ApplicationController
  before_action :set_inbox_table, only: [:show, :edit, :update, :destroy]

  # GET /inbox_tables
  # GET /inbox_tables.json
  def index
    @inbox_tables = InboxTable.all
  end

  # GET /inbox_tables/1
  # GET /inbox_tables/1.json
  def show
  end

  # GET /inbox_tables/new
  def new
    @inbox_table = InboxTable.new
  end

  # GET /inbox_tables/1/edit
  def edit
  end

  # POST /inbox_tables
  # POST /inbox_tables.json
  def create
    @inbox_table = InboxTable.new(inbox_table_params)

    respond_to do |format|
      if @inbox_table.save
        format.html { redirect_to @inbox_table, notice: 'Inbox table was successfully created.' }
        format.json { render :show, status: :created, location: @inbox_table }
      else
        format.html { render :new }
        format.json { render json: @inbox_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inbox_tables/1
  # PATCH/PUT /inbox_tables/1.json
  def update
    respond_to do |format|
      if @inbox_table.update(inbox_table_params)
        format.html { redirect_to @inbox_table, notice: 'Inbox table was successfully updated.' }
        format.json { render :show, status: :ok, location: @inbox_table }
      else
        format.html { render :edit }
        format.json { render json: @inbox_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inbox_tables/1
  # DELETE /inbox_tables/1.json
  def destroy
    @inbox_table.destroy
    respond_to do |format|
      format.html { redirect_to inbox_tables_url, notice: 'Inbox table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inbox_table
      @inbox_table = InboxTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inbox_table_params
      params.fetch(:inbox_table, {})
    end
end

app/helpers/inbox_tables_helper.rb
module InboxTablesHelper
end

app/views/inbox_tables/_form.html.erb
<%= form_with(model: inbox_table, local: true) do |form| %>
  <% if inbox_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inbox_table.errors.count, "error") %> prohibited this inbox_table from being saved:</h2>

      <ul>
        <% inbox_table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inbox_tables/edit.html.erb
<h1>Editing Inbox Table</h1>

<%= render 'form', inbox_table: @inbox_table %>

<%= link_to 'Show', @inbox_table %> |
<%= link_to 'Back', inbox_tables_path %>

app/views/inbox_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inbox Tables</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inbox_tables.each do |inbox_table| %>
      <tr>
        <td><%= link_to 'Show', inbox_table %></td>
        <td><%= link_to 'Edit', edit_inbox_table_path(inbox_table) %></td>
        <td><%= link_to 'Destroy', inbox_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inbox Table', new_inbox_table_path %>

app/views/inbox_tables/new.html.erb
<h1>New Inbox Table</h1>

<%= render 'form', inbox_table: @inbox_table %>

<%= link_to 'Back', inbox_tables_path %>

app/views/inbox_tables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inbox_table_path(@inbox_table) %> |
<%= link_to 'Back', inbox_tables_path %>