config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do
  resources :inbox_tables
  resources :app_schedules
  resources :special_requirements
  resources :app_times
  resources :app_durations
  resources :services
  resources :users, only: [:index]
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    devise_scope :user do
      post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  devise_for :users
  get 'active-sessions', to: "app_schedules#active_sessions"
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'app_schedules', to: 'model#app_schedules', defaults: { format: 'csv'}

end

app/models/app_duration.rb
class AppDuration < ApplicationRecord
    has_many :app_schedules

    validates :duration, presence: true
    validates_uniqueness_of :duration
    validates_uniqueness_of :durationPrice
    validates :durationPrice, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates_uniqueness_of :duration, :durationPrice

    
end

app/controllers/app_durations_controller.rb
class AppDurationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_app_duration, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin, only: [:index, :new, :edit, :show, :destory, :update]

  # GET /app_durations
  # GET /app_durations.json
  def index
    @app_durations = AppDuration.all
  end

  # GET /app_durations/1
  # GET /app_durations/1.json
  def show
  end

  # GET /app_durations/new
  def new
    @app_duration = AppDuration.new
  end

  # GET /app_durations/1/edit
  def edit
  end

  # POST /app_durations
  # POST /app_durations.json
  def create
    @app_duration = AppDuration.new(app_duration_params)

    respond_to do |format|
      if @app_duration.save
        format.html { redirect_to @app_duration, notice: 'Appointment duration was successfully created.' }
        format.json { render :show, status: :created, location: @app_duration }
      else
        format.html { render :new }
        format.json { render json: @app_duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_durations/1
  # PATCH/PUT /app_durations/1.json
  def update
    respond_to do |format|
      if @app_duration.update(app_duration_params)
        format.html { redirect_to @app_duration, notice: 'Appointment duration was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_duration }
      else
        format.html { render :edit }
        format.json { render json: @app_duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_durations/1
  # DELETE /app_durations/1.json
  def destroy
    @app_duration.destroy
    respond_to do |format|
      format.html { redirect_to app_durations_url, notice: 'Appointment duration was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_duration
      @app_duration = AppDuration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_duration_params
      params.require(:app_duration).permit(:duration, :durationPrice)
    end
    def must_be_admin
      unless current_user.admin?
        redirect_to app_schedules_path, alert: "You don't have access to this page."
      end
    end
end

app/helpers/app_durations_helper.rb
module AppDurationsHelper
end

app/views/app_durations/_form.html.erb
<%= form_with(model: app_duration, local: true) do |form| %>
  <% if app_duration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_duration.errors.count, "error") %> prohibited this app_duration from being saved:</h2>

      <ul>
        <% app_duration.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field px-16 items-center justify-between max-w-md m-auto">
    <%= form.label :duration_in_minutes, class: "label" %>
    <%= form.number_field :duration, class: "input" %>
  </div>

  <div class="field pt-8 px-16 items-center justify-between max-w-md m-auto">
    <%= form.label :Price_For_Duration, class: "label" %>
    <%= form.text_field :durationPrice, class: "input" %>
  </div>

  <div class="actions text-center p-10">
    <%= form.submit "Create a New Appointment Duration", class:"cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 mb-4 inline-block rounded" %>
  </div>
<% end %>

app/views/app_durations/edit.html.erb
<!-- alert
<p id="notice"><%= notice %></p>
-->

<div class="container w-full mx-auto flex flex-col items-center justify-center px-2 my-12">
  <div class="bg-white px-6 py-8 border rounded-lg shadow-md text-black w-full">
    <h1 class="pb-6 text-3xl text-center font-semibold text-pink-700">Editing</h1>
    <p class="mb-8 text-2xl text-center">Appointment Durations</p>


<%= render 'form', app_duration: @app_duration %>

    <div class="py-10 text-center">
        <%= link_to 'Show', @app_duration , class:"cursor-pointer font-semibold border border-pink-700 hover:border-pink-900 mr-3 px-5 py-2 inline-block text-pink-700 hover:text-pink-900 rounded"%>
        <%= link_to 'Back', app_durations_path , class:"cursor-pointer font-semibold border border-pink-700 hover:border-pink-900 mr-3 px-5 py-2 inline-block text-pink-700 hover:text-pink-900 rounded"%>
    </div>

  </div>
</div>

app/views/app_durations/index.html.erb
<!-- alert
<p id="notice"><%= notice %></p>
-->

<style>
  .dropdown{
    position:relative;
    display:inline-block;
  }
  .drop-content{
    display:none ;
    position: absolute;
    z-index:1;
  }
  .drop-content a{
    display:block;
  }
  .dropdown:hover .drop-content{
    display:block;
  }
  .down {
    transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
  }
  i {
    border: solid gray;
    border-width: 0 3px 3px 0;
    display: inline-block;
    padding: 3px;
  }
</style>

<!-- the white portion -->
<div class="container w-full mx-auto flex flex-col items-center justify-center px-2 my-12">
  <div class="bg-white px-6 py-8 border rounded-lg shadow-md text-black w-full">
    <h1 class="pb-6 text-3xl text-center font-semibold text-pink-700">Current Durations</h1>
    <p class="mb-8 text-2xl text-center">Appointment Durations</p>

    <!-- table -->
    <table class="w-full">
      <thead>
      <tr class="bg-gray-300 border border-gray-400">
        <th class="py-4">Duration Length in Minutes</th>
        <th class="py-4">Price</th>
        <th class="py-4" colspan="3">Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @app_durations.each do |app_duration| %>
        <tr class="content-center border-b border-t hover:bg-pink-200">
          <td class="w-full text-center px-4 py-2"><%= app_duration.duration %></td>
          <td class="w-full px-12 py-2">$<%= app_duration.durationPrice %></td>
          <td class="w-full px-4 py-2">
            <div class="dropdown">
              <button class=" shadow-md border border-gray-500 cursor-pointer font-semibold bg-white hover:bg-gray-400 text-white px-5 py-2 inline-block rounded"><i class="arrow down"></i></button>
              <div class="drop-content right-0 mt-0 shadow-md w-32 bg-white rounded-lg py-2 text-center">
                <%= link_to 'Show', app_duration , class:"block px-4 py-2 text-gray-800 hover:bg-indigo-500 hover:text-white" %>
                <%= link_to 'Edit', edit_app_duration_path(app_duration) , class:"block px-4 py-2 text-gray-800 hover:bg-indigo-500 hover:text-white" %>
                <%= link_to 'Remove', app_duration, method: :delete, data: { confirm: 'Are you sure?' } , class:"block px-4 py-2 text-gray-800 hover:bg-red-600 hover:text-white" %>
              </div>
            </div>
          </td>
      <% end %>
      </tbody>
    </table>

    <div class="py-10 text-center">
      <%= link_to 'Add a New Time Duration', new_app_duration_path, class:"cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 mb-4 inline-block rounded" %>
    </div>

  </div>
</div>

app/views/app_durations/new.html.erb
<!-- alert
<p id="notice"><%= notice %></p>
-->

<div class="container w-full mx-auto flex flex-col items-center justify-center px-2 my-12">
  <div class="bg-white px-6 py-8 border rounded-lg shadow-md text-black w-full">
    <h1 class="pb-6 text-3xl text-center font-semibold text-pink-700">Creating New</h1>
    <p class="mb-8 text-2xl text-center">Appointment Duration</p>

<%= render 'form', app_duration: @app_duration %>

    <div class="py-10 text-center">
      <%= link_to 'Back', app_durations_path, class:"cursor-pointer font-semibold border border-pink-700 hover:border-pink-900 mr-3 px-5 py-2 inline-block text-pink-700 hover:text-pink-900 rounded" %>
    </div>

  </div>
</div>

app/views/app_durations/show.html.erb
<!-- alert
<p id="notice"><%= notice %></p>
-->

<div class="container w-full mx-auto flex flex-col items-center justify-center px-2 my-12">
  <div class="bg-white px-6 py-8 border rounded-lg shadow-md text-black w-full">
    <h1 class="pb-6 text-3xl text-center font-semibold text-pink-700">Showing</h1>
    <p class="mb-8 text-2xl text-center">Appointment Duration Details</p>


<table class="w-full">
  <thead>
  <tr class="bg-gray-300 border border-gray-400">
    <th class="py-4">Duration</th>
    <th class="py-4">Price</th>
    <th class="py-4" colspan="2">Actions</th>
  </tr>
  </thead>

  <tbody>

  <tr class="content-center border-b border-t hover:bg-pink-200">
    <td class="w-full text-center px-4 py-2">
      <%= @app_duration.duration %>
    </td>
    <td class="w-full px-12 py-2">
      $<%= @app_duration.durationPrice %>
    </td>
    <td class="w-full px-4 py-2">
      <%= link_to 'Edit', edit_app_duration_path(@app_duration) , class:"cursor-pointer font-semibold bg-gray-500 hover:bg-green-600 text-white px-5 py-2 inline-block rounded"%>
    </td>
  </tr>

  </tbody>
</table>


<div class="py-10 text-center">
  <%= link_to 'Back', app_durations_path , class:"cursor-pointer font-semibold border border-pink-700 hover:border-pink-900 mr-3 px-5 py-2 inline-block text-pink-700 hover:text-pink-900 rounded"%>
</div>

  </div>
</div>