config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do
  resources :inbox_tables
  resources :app_schedules
  resources :special_requirements
  resources :app_times
  resources :app_durations
  resources :services
  resources :users, only: [:index]
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    devise_scope :user do
      post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  devise_for :users
  get 'active-sessions', to: "app_schedules#active_sessions"
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'app_schedules', to: 'model#app_schedules', defaults: { format: 'csv'}

end

app/models/app_schedule.rb
class AppSchedule < ApplicationRecord
  belongs_to :user
            #  foreign_key: "user_id"
  belongs_to :service
            #  foreign_key: "service_id" 
  belongs_to :app_duration
            #  foreign_key: "appduration_id" 
  belongs_to :special_requirement
            #  foreign_key: "specialrequirement_id" 
  belongs_to :app_time
            #  foreign_key: "app_time_id"
             

  validates :homeAddress, presence: true
  validates :homeType, presence: true
  validates :state, presence: true, length: {maximum: 2}, inclusion: { in: %w(NC), message: "%{value} is not a valid state" }
  validates :city, presence: true
  validates :zipcode, presence: true
  validates :zipcode, length: { is: 5 }
  

CSV_HEADER = %w{Appointment_Time_Slot Client_Name Service Service_Price Duration Duration_Price Home_Address Home_Type Suite_Number City State Zipcode Comment Special_Requirements}
  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << CSV_HEADER
      all.each do |app_schedule|
        csv << [
          app_schedule.app_time.appDate,
          app_schedule.user.name,
          app_schedule.service.serviceName,
          app_schedule.service.servicePrice,
          app_schedule.app_duration.duration,
          app_schedule.app_duration.durationPrice,
          app_schedule.homeAddress,
          app_schedule.homeType,
          app_schedule.suiteNumber,
          app_schedule.city,
          app_schedule.state,
          app_schedule.zipcode,
          app_schedule.comment,
          app_schedule.special_requirement.requirementDesc
            ]
      end
    end
  end

  def start_time
    self.app_time.appDate
  end

end

app/controllers/app_schedules_controller.rb
class AppSchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_app_schedule, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin, only: [:active_sessions]


  # GET /app_schedules
  # GET /app_schedules.json
  #def import     @software = Software.find(params[:software_id])     Code.import(@software, params[:file])     redirect_to codes_path, notice: 'Codes were successfully uploaded!'   end

  def index
    if current_user.admin?
    @app_schedules = AppSchedule.all

    respond_to do |format|
      format.html
      format.csv { send_data @app_schedules.to_csv, filename: "appsched-#{Date.today}.csv"}
    end
    else
      @app_schedules = current_user.app_schedules.where(user_id: current_user)
      respond_to do |format|
        format.html
        format.csv { send_data @app_schedules.to_csv, filename: "appsched-#{Date.today}.csv"}
      end
    end
  end

  # GET /app_schedules/1
  # GET /app_schedules/1.json
  def show
  end

  # GET /app_schedules/new
  def new
    @app_schedule = AppSchedule.new
  end

  # GET /app_schedules/1/edit
  def edit
  end

  # POST /app_schedules
  # POST /app_schedules.json
  def create
    @app_schedule = AppSchedule.new(app_schedule_params)
    @app_schedule.user_id = current_user.id
#   


    respond_to do |format|
      if @app_schedule.save
        format.html { redirect_to @app_schedule, notice: 'Appointment was successfully scheduled. Please check your email for confirmation and further details!' }
        format.json { render :show, status: :created, location: @app_schedule }
        @app_schedule.app_time.update_attribute(:booked, true)
        #method from AppointmentMailer that is supposed to prepare mail to be sent
        AppointmentMailer.with(app_schedule: @app_schedule).notify_appointment.deliver!
        AppointmentMailer.with(app_schedule: @app_schedule, user: current_user).appointment_scheduled.deliver!
        #AppointmentMailer.with(app_schedule: @app_schedule, user: current_user).appointment_scheduled.deliver!
       

      else
        format.html { render :new }
        format.json { render json: @app_schedule.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /app_schedules/1
  # PATCH/PUT /app_schedules/1.json
  def update
    respond_to do |format|
      if @app_schedule.update(app_schedule_params)
        AppointmentMailer.with(app_schedule: @app_schedule).update_appointment.deliver!
        AppointmentMailer.with(app_schedule: @app_schedule).notify_appointment_update.deliver!
        format.html { redirect_to @app_schedule, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_schedule }
      else
        format.html { render :edit }
        format.json { render json: @app_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_schedules/1
  # DELETE /app_schedules/1.json
  def destroy
    @app_schedule.destroy
    respond_to do |format|
      @app_schedule.app_time.update_attribute(:booked, false)
      AppointmentMailer.with(app_schedule: @app_schedule).cancel_appointment.deliver!
      AppointmentMailer.with(app_schedule: @app_schedule).notify_appointment_cancel.deliver!
      format.html { redirect_to app_schedules_url, notice: 'Appointment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def active_sessions
    @active_sessions = AppSchedule.where("appDate > ?", Time.now)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_schedule
      @app_schedule = AppSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_schedule_params
      params.require(:app_schedule).permit(:homeAddress, :homeType, :suiteNumber, :city, :state, :zipcode, :comment, :appDate, :user_id, :service_id, :appduration_id, :specialrequirement_id, :app_time_id)
    end

  def must_be_admin
    unless current_user.admin?
      redirect_to app_schedules_path, alert: "You don't have access to this page."
    end
  end



end

app/helpers/app_schedules_helper.rb
module AppSchedulesHelper
end

app/views/app_schedules/_app_schedules_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%#= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't scheduled an appointment yet.</h1>
  <%= link_to "Schedule a New Appointment", new_app_schedule_path, class: "cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded" %>
</div>

app/views/app_schedules/_app_schedules_landing.html.erb
<nav class="mb-4 flex justify-center">
  <ul id="nav-tab" class="tabs list-reset  flex flex-col lg:flex-row md:flex-row  text-center ">

<% if current_user.admin? %>




      <%= link_to "#calendar", class:"cursor-pointer object-cover font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded mb-4 w-auto" do %>
      Calendar

      <% end %>




      <!-- Hide Export Code
      <li><a href="/app_schedules.csv"><button class="btn btn-success cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded">Export Appointments</button></a></li>
      -->



        <%= link_to "/app_schedules.csv", class:"cursor-pointer object-cover font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded mb-4 w-auto " do%>
          Export Appointments

        <%end %>



  <% end %>




      <%= link_to "#all-appointments", class: "cursor-pointer object-cover font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded mb-4 w-auto " do %>
      All Appointments

      <% end %>




  </ul>

</nav>

<div class="bg-white p-10 border rounded">
  <div id="all-meetings" class="tab-panel">

    <h1>Scheduled Appointments</h1>
    <% app_schedules.each do |app_schedule| %>
      <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
        <div class="flex-1 flex justify-between">
          <div>
            <%= link_to app_schedule.user.name, app_schedule, class: "link mr-4" %>
          </div>
          <div>
            <%= readable_time(app_schedule.app_time.appDate) %>
          </div>
        </div>
        <%= link_to "Cancel Appointment", app_schedule, method: :delete, data: { confirm: "Are you sure?." }, class: "btn btn-destroy ml-4"  if admin? %>
      </div>
    <% end %>
  </div>

  <div id="calendar" class="tab-panel active">
    <h2>Appointment Calendar</h2>
    <div id="meeting-calendar">
      <%= render "calendar", app_schedules: app_schedules%>
    </div>
  </div>
</div>

app/views/app_schedules/_calendar.html.erb
<%= month_calendar events: app_schedules do |date, app_schedules| %>
  <%= date %>
  <% app_schedules.each do |app_schedule| %>
    <div>
      <%= link_to app_schedule.user.name, app_schedule, class: "link" %>
    </div>
  <% end %>
<% end %>

app/views/app_schedules/_form.html.erb
<%= form_with(model: app_schedule, local: true, class: "meeting-form") do |form| %>
  <% if app_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_schedule.errors.count, "error") %> prohibited this app_schedule from being saved:</h2>

      <ul>
        <% app_schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Address, class: "label required" %>
    <%= form.text_field :homeAddress, class: "input", :required => true %>
  </div>

  <div class="field">
    <%= form.label :home_type, class: "label" %>
    <%= form.text_field :homeType, class: "input",:required => true, placeholder: "1 Story, 2 Story, Apartment, etc." %>
  </div>

  <div class="field">
    <%= form.label :suite_number, class: "label" %>
    <%= form.text_field :suiteNumber, class: "input", placeholder: "Please fill out if in apartment, condo, etc" %>
  </div>

  <div class="field">
    <%= form.label :city, class: "label required" %>
    <%= form.text_field :city, class: "input", :required => true

 %>
  </div>

  <div class="field">
    <%= form.label :state, class: "label required" %>
    <%= form.text_field :state, class: "input", :required => true, value: "NC"

 %>
  </div>

  <div class="field">
    <%= form.label :zipcode, class: "label required" %>
    <%= form.text_field :zipcode, class: "input", :required => true %>
  </div>

    <div class="field">
    <%= form.label :comment, class: "label" %>
    <%= form.text_field :comment, class: "input", placeholder: "Enter gate codes, entrance instructions, etc" %>
  </div>

  <div class="mb-4">
    <%= form.label :service, class: "label r" %>
    <%= collection_select(:app_schedule, :service_id, Service.all, :id, :serviceName, {}) %>
  </div>

  <div class="mb-4">
    <%= form.label :duration_in_minutes, class: "label" %>
    <%= collection_select(:app_schedule, :appduration_id, AppDuration.all, :id, :duration, {}) %>
  </div>

  <div class="mb-4">
    <%= form.label :massage_intensity, class: "label" %>
    <%= collection_select(:app_schedule, :specialrequirement_id, SpecialRequirement.all, :id, :requirementDesc, {}) %>
  </div>

  <div class="mb-4">
    <%= form.label :select_appointment_time, class: "label" %>
    <%= collection_select(:app_schedule, :app_time_id, AppTime.where(booked: false), :id, :short_time, {}) %>
  </div>

  <div class="actions">
    <%= form.submit "Schedule Your Appointment", class:"cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 mb-4 inline-block rounded"%>
  </div>
  <br>
  <br>

<!--
  <div class="px-4 lg:px-0 m-auto mt-8 lg:max-w-4xl flex flex-wrap items-start justify-between text-gray-700">
    <h2 class="text-lg font-bold">Pricing</h2>
    <p class="mb-2">Please note that prices will increase based on session duration, up-charges on selected services, and travel distance. A $20 travel fee will be applied to the appointment via e-mail confirmation. Failure to pay the deposit within 24 hours of booking, may result in the cancellation of your appointment. Additional charges may be added to the final cost of the appointment upon completion which will account for travel distances exceeding the first 20 miles ($1 per mile after).</p>
    <h2 class="text-lg font-bold">Cancellation Policy</h2>
    <p class="mb-2">A 24-hour advance notice is required when cancelling or rescheduling an appointment. This allows for the opportunity for someone else to schedule an appointment. If you are unable to give 24 hours advance notice, the $20 deposit fee towards travel will not be refunded.</p>
  </div>-->

<% end %>

app/views/app_schedules/active_sessions.html.erb
<div class="container m-auto bg-white my-10 border border-grey-light p-10">
  <h1 class="text-indigo-darker">Active Sessions</h1>

  <% @active_sessions.each do |app_schedule| %>
    <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
      <div class="flex-1 flex justify-between">
        <div>
          <%= link_to app_schedule.user.name, app_schedule, class: "link mr-4" %>
        </div>
        <div>
          <%= readable_time(app_schedule.app_time.appDate) %>
        </div>
      </div>

      <%= link_to 'Cancel Appointment', app_schedule, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-destroy ml-4" if admin? %>
    </div>
  <% end %>
</div>

app/views/app_schedules/edit.html.erb
<h1>Editing App Schedule</h1>

<%= render 'form', app_schedule: @app_schedule %>

<%= link_to 'Show', @app_schedule %> |
<%= link_to 'Back', app_schedules_path %>

app/views/app_schedules/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.app_schedules.any? %>
    <%= render "app_schedules_cta" unless admin? %>
  <% else %>
    <%= render "app_schedules_landing", app_schedules: @app_schedules %>
  <% end %>

  <% if current_user.admin? %>
    <%= render "app_schedules_landing", app_schedules: @app_schedules %>
  <% end %>
</div>

app/views/app_schedules/new.html.erb
<div class="container max-w-xl mx-auto flex flex-col items-center justify-center px-2 my-12">
  <div class="bg-white px-6 py-8 border rounded-lg shadow-md text-black w-full">
    <h1 class="mb-8 text-3xl text-center"><strong>Schedule Your Appointment Now! </strong> </h1>

<%= render 'form', app_schedule: @app_schedule %>

<%= link_to 'Back', app_schedules_path, class:"cursor-pointer font-semibold border border-pink-700 hover:border-pink-900 mr-3 px-5 py-2 inline-block text-pink-700 hover:text-pink-900 rounded" %>

app/views/app_schedules/show.html.erb
<div class="max-w-lg my-10 m-auto">
  <div class="p-10 bg-white border border-grey-light rounded">

    <div class="flex flex-wrap justify-between items-center mb-5">
      <h1><%= @app_schedule.user.name %></h1>
      <%= link_to 'Edit', edit_app_schedule_path(@app_schedule), class: "btn btn-destroy"  if admin? %>
      <%= link_to "Cancel Appointment", app_schedule_path(@app_schedule), method: :delete, data: { confirm: "Are you sure you want to cancel? "}, class: "btn btn-destroy bg-pink-700 hover:bg-pink-900 text-white font-bold"%>

    </div>



    <div class="border p-6 bg-grey-lighter mb-5 flex items-center justify-between">
      <p class="py-3 px-4 text-sm text-pink">
        Appointment Time Slot: <span class="font-bold"><%= readable_time(@app_schedule.app_time.appDate) %></span>
        <br>
        Appointment Address: <span class="font-bold"><%= @app_schedule.homeAddress %></span>
        <span class="font-bold"><%= @app_schedule.city %> </span>
        <span class="font-bold"><%= @app_schedule.state %> </span>
        <span class="font-bold"><%= @app_schedule.zipcode %></span>
        <br>
        Additional Comments: <span class="font-bold"><%= @app_schedule.comment %></span>
        <br>
        Service: <span class="font-bold"><%= @app_schedule.service.serviceName %></span>
        <br>
        Service Price: <span class="font-bold"><%= @app_schedule.service.servicePrice %></span>
        <br>
        Duration(Minutes): <span class="font-bold"><%= @app_schedule.app_duration.duration %></span>
        <br>
        Duration Price: <span class="font-bold"><%= @app_schedule.app_duration.durationPrice %></span>
        <br>
        Pressure Intensity: <span class="font-bold"><%= @app_schedule.special_requirement.requirementDesc %></span>
        <br>



      </p>
      </p>
    </div>
  </div>
</div>