config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do
  resources :inbox_tables
  resources :app_schedules
  resources :special_requirements
  resources :app_times
  resources :app_durations
  resources :services
  resources :users, only: [:index]
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    devise_scope :user do
      post 'users/sign_up', to: 'devise/registrations#create'
  end
  
  devise_for :users
  get 'active-sessions', to: "app_schedules#active_sessions"
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'app_schedules', to: 'model#app_schedules', defaults: { format: 'csv'}

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HandsOfLyfe Massage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body class="bg-gray-100">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

  <nav class="flex flex-wrap lg:flex-none items-center justify-between bg-gray-100 p-3">
    <div class="w-auto text-pink-700 text-2xl font-semibold lg:ml-12">
      <p><div style="font-family: 'Marthin Slant', serif;"><%= link_to "HandsOfLyfe", root_path%></p></div>
    </div>
    <% if user_signed_in? %>
      <div class="w-auto text-pink-600 text-right">
        Welcome, <%= current_user.name %>
      </div>
    <% else %>
    <% end %>
    <div class="block lg:hidden mr-8">
      <button id="nav-toggle" class="flex items-center px-3 py-2 rounded text-pink-600 border border-pink-600">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="hidden w-full flex-grow lg:flex lg:flex-none lg:w-auto lg:items-center pt-6 lg:pt-0" id="nav-content">
      <ul class="list-reset lg:flex justify-end flex-1 items-center">
      <% unless admin? %>
        <li class="mr-2">
          <a class="inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" href="/#about">About</a>
        </li>
        <li class="mr-2">
          <a class="inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" href="/#services">Services</a>
        </li>
        <% end %>
        <li class="mr-2">
        <%= link_to "Users", users_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" if admin? %>
        </li>
        <li class="mr-2">
        <%= link_to "Appointment Dashboard", app_schedules_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" if admin? %>
        </li>
        <li class="mr-2">
        <%= link_to "Schedule an Appointment", new_app_schedule_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" unless admin? %>
        </li>
        <% if user_signed_in? %>
        <li class="mr-2">
          <%= link_to "My Appointments", app_schedules_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" unless admin? %>
        </li>
        <% else %>
        <% end %>
        <li class="mr-2">
          <%= link_to "Set up Times", app_times_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" if admin? %>
        </li>
        <li class="mr-2">
          <%= link_to "Create Services", services_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" if admin? %>
        </li>
        <li class="mr-2">
        <%= link_to "Set Time Durations", app_durations_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" if admin? %>      
        </li>
        <li class="mr-2">
        <%= link_to "Set Massage Requirements", special_requirements_path, class: "inline-block text-gray-600 font-semibold hover:text-pink-700 py-2 px-4" if admin? %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class:"cursor-pointer font-semibold bg-pink-700 hover:bg-pink-900 text-white mr-3 px-5 py-2 inline-block rounded" %>
        <%= link_to "Sign Up", new_user_registration_path, class:"cursor-pointer font-semibold border border-pink-700 hover:border-pink-900 mr-3 px-5 py-2 inline-block text-pink-700 hover:text-pink-900 rounded" %>
      <% end %>
    </div>
  </nav>

  <script>
      //Javascript to toggle the menu
      document.getElementById('nav-toggle').onclick = function(){
          document.getElementById("nav-content").classList.toggle("hidden");
      }
  </script>

    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>

  <!-- Footer -->

  <div class="lg:flex text-center justify-center max-w-6xl mx-auto py-6 border-t border-gray-400">

    <div class="ml-4">©2019 HandsOfLyfe |</div>
    <div class="ml-2"> Made with Love <span class="text-pink-600">♥</span> by Cosmic Solutions</div>

    <div class="flex justify-center lg:mx-auto lg:my-auto mx-8 my-4">
      <a href="https://facebook.com/handsoflyfe" target="_blank" class="mx-3 h-8 w-8">
        <img src="/assets/facebook.svg" alt="Facebook Icon">
      </a>

      <a href="https://instagram.com/handsoflyfe" target="_blank" class="mx-3 h-8 w-8">
      <img src="/assets/instagram.svg" alt="Instagram Icon">
      </a>

      <a href="mailto:handsoflyfe@gmail.com" target="_blank" class="mx-3 h-8 w-8">
        <img src="/assets/email.svg" alt="Email Icon">
      </a>
    </div>

  </div>
  </body>
</html>